import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
import { Suspense } from "react";

// Dynamically import NavBar and Footer components
const NavBar = dynamic(() => import("@/components/Navbar"), { ssr: false });
const Footer = dynamic(() => import("@/components/Footer"), { ssr: false });

// Fonts setup
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "WebOrbit",
  description: "Generated by create next app",
};

// Loading fallback component
const LoadingFallback = () => <div>Loading...</div>;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Lazy-loaded NavBar */}
        <NavBar />

        {/* Suspense for lazy loading the children */}
        <Suspense fallback={<LoadingFallback />}>
          {children}
        </Suspense>

        {/* Lazy-loaded Footer */}
        <Footer />
      </body>
    </html>
  );
}
